server:
  port: 0 # 8081 # 0 # 랜텀포트

spring:
  application:
    name: msa-client-app-01

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defautZone: http://localhost:8761/eureka